import Swal from 'sweetalert2';
import 'sweetalert2/src/sweetalert2.scss';
import axios from 'axios';
import './js/mobile-menu-function';
import './js/subscription';
import './js/exercises-modal';
import './js/modals-functions';
import './js/send-rating-modal';
import './js/quote';
import './js/add-to-favorites';
