import './js/mobile-menu-function';
import './js/subscription';
import './js/exercises-modal';
import './js/modals-functions';
import './js/send-rating-modal';
import './js/quote';
import './js/policy';
import './js/add-to-favorites';
import './js/exercises';
